test: a b c
a:
	gcc sendera.c -o sendera -Wall
	gcc catchera.c -o catchera -Wall
b:
	gcc senderb.c -o senderb -Wall
	gcc catcherb.c -o catcherb -Wall
c:
	gcc senderc.c -o senderc -Wall
	gcc catcherc.c -o catcherc -Wall
clean:
	rm -rf sendera
	rm -rf catchera
	rm -rf senderb
	rm -rf catcherb
	rm -rf senderc
	rm -rf catcherc
