make: v1 v2 v3 v4 v5
v1:
	gcc main.c -o v1 -Wall -lpthread -D PKT_1
v2:
	gcc main.c -o v2 -Wall -lpthread -D PKT_2
v3:
	gcc main.c -o v3 -Wall -lpthread -D PKT_3
v4:
	gcc main.c -o v4 -Wall -lpthread -D PKT_4
v5:
	gcc main.c -o v5 -Wall -lpthread -D PKT_5
clean:
	rm -rf v1
	rm -rf v2
	rm -rf v3
	rm -rf v4
	rm -rf v5
